# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.20.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
rg = np.random.default_rng(1)
a = rg.random((2,3,5))
a

array([[[0.51182162, 0.9504637 , 0.14415961, 0.94864945, 0.31183145],
        [0.42332645, 0.82770259, 0.40919914, 0.54959369, 0.02755911],
        [0.75351311, 0.53814331, 0.32973172, 0.7884287 , 0.30319483]],

       [[0.45349789, 0.1340417 , 0.40311299, 0.20345524, 0.26231334],
        [0.75036467, 0.28040876, 0.48519097, 0.9807372 , 0.96165719],
        [0.72478994, 0.54122686, 0.2768912 , 0.16065201, 0.96992541]]])

In [39]:
# Method 2
a = np.random.random((2,3,5))
a

array([[[0.89215633, 0.60705963, 0.25017359, 0.836631  , 0.81740944],
        [0.87145029, 0.12817003, 0.82305319, 0.62359111, 0.32060717],
        [0.80951182, 0.36173692, 0.62636186, 0.05577355, 0.83049614]],

       [[0.58401329, 0.32146506, 0.35057923, 0.57809769, 0.10897124],
        [0.16616249, 0.33654086, 0.44911691, 0.26108265, 0.78858211],
        [0.3570252 , 0.32519471, 0.68106632, 0.95738093, 0.21358816]]])

In [41]:
# Method 3
aa=np.random.rand(2,3,5)
aa


array([[[0.81134608, 0.99867837, 0.18003248, 0.99671786, 0.43382988],
        [0.00804349, 0.05555053, 0.84768972, 0.82122068, 0.75946935],
        [0.37081556, 0.75719909, 0.72577646, 0.68327294, 0.6511069 ]],

       [[0.73364761, 0.52969434, 0.82914785, 0.4066229 , 0.01150334],
        [0.51457006, 0.1510668 , 0.2881668 , 0.6449679 , 0.82247334],
        [0.87245641, 0.46806353, 0.42727356, 0.92491722, 0.77239239]]])

#### 4. Print *a*.


In [42]:
# your code here
print(a)

[[[0.89215633 0.60705963 0.25017359 0.836631   0.81740944]
  [0.87145029 0.12817003 0.82305319 0.62359111 0.32060717]
  [0.80951182 0.36173692 0.62636186 0.05577355 0.83049614]]

 [[0.58401329 0.32146506 0.35057923 0.57809769 0.10897124]
  [0.16616249 0.33654086 0.44911691 0.26108265 0.78858211]
  [0.3570252  0.32519471 0.68106632 0.95738093 0.21358816]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [18]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [19]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [23]:
# your code here
print (a.size)
print (b.size)


30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [43]:
# your answer here
c=a + b
# we couldn't add a and b beacause they don't have same shape


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [27]:
# your code here
c = b.reshape(2,3,5)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [46]:
# your code/answer here
d = a + c 
print(d)

[[[1.89215633 1.60705963 1.25017359 1.836631   1.81740944]
  [1.87145029 1.12817003 1.82305319 1.62359111 1.32060717]
  [1.80951182 1.36173692 1.62636186 1.05577355 1.83049614]]

 [[1.58401329 1.32146506 1.35057923 1.57809769 1.10897124]
  [1.16616249 1.33654086 1.44911691 1.26108265 1.78858211]
  [1.3570252  1.32519471 1.68106632 1.95738093 1.21358816]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [51]:
# your code/answer here
print(a)

print(d)
print(a.size)
print(d.size)
# they have the same shape

[[[0.89215633 0.60705963 0.25017359 0.836631   0.81740944]
  [0.87145029 0.12817003 0.82305319 0.62359111 0.32060717]
  [0.80951182 0.36173692 0.62636186 0.05577355 0.83049614]]

 [[0.58401329 0.32146506 0.35057923 0.57809769 0.10897124]
  [0.16616249 0.33654086 0.44911691 0.26108265 0.78858211]
  [0.3570252  0.32519471 0.68106632 0.95738093 0.21358816]]]
[[[1.89215633 1.60705963 1.25017359 1.836631   1.81740944]
  [1.87145029 1.12817003 1.82305319 1.62359111 1.32060717]
  [1.80951182 1.36173692 1.62636186 1.05577355 1.83049614]]

 [[1.58401329 1.32146506 1.35057923 1.57809769 1.10897124]
  [1.16616249 1.33654086 1.44911691 1.26108265 1.78858211]
  [1.3570252  1.32519471 1.68106632 1.95738093 1.21358816]]]
30
30


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [52]:
# your code here
e = a * c
print(e)

[[[0.89215633 0.60705963 0.25017359 0.836631   0.81740944]
  [0.87145029 0.12817003 0.82305319 0.62359111 0.32060717]
  [0.80951182 0.36173692 0.62636186 0.05577355 0.83049614]]

 [[0.58401329 0.32146506 0.35057923 0.57809769 0.10897124]
  [0.16616249 0.33654086 0.44911691 0.26108265 0.78858211]
  [0.3570252  0.32519471 0.68106632 0.95738093 0.21358816]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [53]:
# your code/answer here
e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [57]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print(d_max)
print(d_min)
print(d_mean)

1.9573809255226515
1.0557735486850754
1.511101630112053


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [64]:
# your code here
f = np.empty((2,3,5))
f


array([[[0.89215633, 0.60705963, 0.25017359, 0.836631  , 0.81740944],
        [0.87145029, 0.12817003, 0.82305319, 0.62359111, 0.32060717],
        [0.80951182, 0.36173692, 0.62636186, 0.05577355, 0.83049614]],

       [[0.58401329, 0.32146506, 0.35057923, 0.57809769, 0.10897124],
        [0.16616249, 0.33654086, 0.44911691, 0.26108265, 0.78858211],
        [0.3570252 , 0.32519471, 0.68106632, 0.95738093, 0.21358816]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [77]:
# your code here
for i1 in range(0,2):
    for i2 in range(0,3):
        for i3 in range(0,5):
            if d_min< d[i1,i2,i3] < d_mean:
                f[i1,i2,i3] = 25
            elif d_mean< d[i1,i2,i3] < d_max:
                f[i1,i2,i3] = 75
            elif d[i1,i2,i3] == d_mean:
                f[i1,i2,i3] = 50
            elif d[i1,i2,i3] == d_min:
                f[i1,i2,i3] = 0
            else:
                f[i1,i2,i3] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [78]:
# your code here
print(f)

[[[ 75.  75.  25.  75.  75.]
  [ 75.  25.  75.  75.  25.]
  [ 75.  25.  75.   0.  75.]]

 [[ 75.  25.  25.  75.  25.]
  [ 25.  25.  25.  25.  75.]
  [ 25.  25.  75. 100.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [79]:
# your code here
g = np.empty((2,3,5),str)
for i1 in range(0,2):
    for i2 in range(0,3):
        for i3 in range(0,5):
            if d_min< d[i1,i2,i3] < d_mean:
                g[i1,i2,i3] = 'B'
            elif d_mean< d[i1,i2,i3] < d_max: 
                g[i1,i2,i3] = 'D'
            elif d[i1,i2,i3] == d_mean:
                g[i1,i2,i3] = 'C'
            elif d[i1,i2,i3] == d_min:
                g[i1,i2,i3] = 'A'
            else:
                g[i1,i2,i3] = 'E'
print(g)

[[['D' 'D' 'B' 'D' 'D']
  ['D' 'B' 'D' 'D' 'B']
  ['D' 'B' 'D' 'A' 'D']]

 [['D' 'B' 'B' 'D' 'B']
  ['B' 'B' 'B' 'B' 'D']
  ['B' 'B' 'D' 'E' 'B']]]
