Step 1: Data Engineering
This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

Read tic-tac-toe.csv into a dataframe.
Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
Convert the categorical values to numeric in all columns.
Separate the inputs and output.
Normalize the input data.



In [ ]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn

# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt

# Keras specific
import keras
from keras.models import Sequential
from keras.layers import Dense
import tensorflow as tf
from tensorflow.keras.utils import to_categorica

In [2]:
from google.colab import files
uploaded = files.upload()

Saving tic tac toe.xlsx to tic tac toe.xlsx


In [4]:
import io
data = pd.read_excel(io.BytesIO(uploaded['tic tac toe.xlsx']))
data

TL TM TR ML MM MR BL BM BR  class
0    x  x  x  x  o  o  x  o  o   True
1    x  x  x  x  o  o  o  x  o   True
2    x  x  x  x  o  o  o  o  x   True
3    x  x  x  x  o  o  o  b  b   True
4    x  x  x  x  o  o  b  o  b   True
..  .. .. .. .. .. .. .. .. ..    ...
953  o  x  x  x  o  o  o  x  x  False
954  o  x  o  x  x  o  x  o  x  False
955  o  x  o  x  o  x  x  o  x  False
956  o  x  o  o  x  x  x  o  x  False
957  o  o  x  x  x  o  o  x  x  False

[958 rows x 10 columns]

In [5]:
data['class'].value_counts()

True     626
False    332
Name: class, dtype: int64

In [6]:
data.replace('x', 1, inplace=True)
data.replace('o', -1, inplace=True)
data.replace('b', 0, inplace=True)
data

TL  TM  TR  ML  MM  MR  BL  BM  BR  class
0     1   1   1   1  -1  -1   1  -1  -1   True
1     1   1   1   1  -1  -1  -1   1  -1   True
2     1   1   1   1  -1  -1  -1  -1   1   True
3     1   1   1   1  -1  -1  -1   0   0   True
4     1   1   1   1  -1  -1   0  -1   0   True
..   ..  ..  ..  ..  ..  ..  ..  ..  ..    ...
953  -1   1   1   1  -1  -1  -1   1   1  False
954  -1   1  -1   1   1  -1   1  -1   1  False
955  -1   1  -1   1  -1   1   1  -1   1  False
956  -1   1  -1  -1   1   1   1  -1   1  False
957  -1  -1   1   1   1  -1  -1   1   1  False

[958 rows x 10 columns]

In [7]:
X=np.array(data.drop('class', axis=1))
y=np.array(data['class'])

In [8]:
#Scaling my data
X_scaled = tf.keras.utils.normalize(X, axis=1)
X_scaled

array([[ 0.33333333,  0.33333333,  0.33333333, ...,  0.33333333,
        -0.33333333, -0.33333333],
       [ 0.33333333,  0.33333333,  0.33333333, ..., -0.33333333,
         0.33333333, -0.33333333],
       [ 0.33333333,  0.33333333,  0.33333333, ..., -0.33333333,
        -0.33333333,  0.33333333],
       ...,
       [-0.33333333,  0.33333333, -0.33333333, ...,  0.33333333,
        -0.33333333,  0.33333333],
       [-0.33333333,  0.33333333, -0.33333333, ...,  0.33333333,
        -0.33333333,  0.33333333],
       [-0.33333333, -0.33333333,  0.33333333, ..., -0.33333333,
         0.33333333,  0.33333333]])

In [ ]:
Step 2: Build Neural Network
To build the neural network, you can refer to your own codes you wrote while following the Deep Learning with Python, TensorFlow, and Keras tutorial in the lesson. It's pretty similar to what you will be doing in this lab.

Split the training and test data.
Create a Sequential model.
Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
Compile the model using adam as the optimizer and sparse_categorical_crossentropy as the loss function. For metrics, use accuracy for now.
Fit the training data.
Evaluate your neural network model with the test data.
Save your model as tic-tac-toe.model.

In [9]:
from sklearn.model_selection import train_test_split
X=data.drop('class',axis=1)
y=data['class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=40)
print(X_train.shape); print(X_test.shape)

(670, 9)
(288, 9)


In [10]:
y_train = to_categorical(y_train,2)
y_test = to_categorical(y_test,2)

unique, counts = np.unique(y, return_counts=True)
dict(zip(unique, counts))

{False: 332, True: 626}

In [11]:
y_train

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]], dtype=float32)

In [12]:
model = Sequential()
model.add(Dense(500, activation='relu', input_dim=9))
model.add(Dense(100, activation='relu'))
#model.add(Dense(50, activation='relu'))
model.add(Dense(2, activation='softmax'))

# Compile the model
model.compile(optimizer='adam', 
              loss='categorical_crossentropy', 
              metrics=['accuracy'])

In [13]:
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
21/21 [==============================] - 2s 3ms/step - loss: 0.5978 - accuracy: 0.6657
Epoch 2/10
21/21 [==============================] - 0s 2ms/step - loss: 0.4752 - accuracy: 0.7701
Epoch 3/10
21/21 [==============================] - 0s 3ms/step - loss: 0.3765 - accuracy: 0.8701
Epoch 4/10
21/21 [==============================] - 0s 3ms/step - loss: 0.2701 - accuracy: 0.9284
Epoch 5/10
21/21 [==============================] - 0s 3ms/step - loss: 0.1731 - accuracy: 0.9761
Epoch 6/10
21/21 [==============================] - 0s 3ms/step - loss: 0.0999 - accuracy: 0.9866
Epoch 7/10
21/21 [==============================] - 0s 2ms/step - loss: 0.0576 - accuracy: 0.9940
Epoch 8/10
21/21 [==============================] - 0s 3ms/step - loss: 0.0337 - accuracy: 1.0000
Epoch 9/10
21/21 [==============================] - 0s 2ms/step - loss: 0.0208 - accuracy: 1.0000
Epoch 10/10
21/21 [==============================] - 0s 3ms/step - loss: 0.0143 - accuracy: 1.0000


In [14]:
pred_test= model.predict(X_test)
scores = model.evaluate(X_test, y_test, verbose=0)
print('Accuracy on test data: {} \n Error on test data: {}'.format(scores[1], 1 - scores[1])) 

Accuracy on test data: 0.9895833134651184 
 Error on test data: 0.010416686534881592


In [15]:
model.save("tic-tac-toe.model")

INFO:tensorflow:Assets written to: tic-tac-toe.model/assets


In [16]:
mdl = tf.keras.models.load_model("tic-tac-toe.model")

In [17]:
import random
ind=[]
for i in range(10): 
    ind.append(random.randint(1, len(X_test)-1))
ind

[280, 8, 78, 134, 25, 115, 106, 17, 128, 52]

In [18]:
X_test.iloc[80]

TL   -1
TM    1
TR   -1
ML    0
MM   -1
MR    1
BL   -1
BM    1
BR    1
Name: 785, dtype: int64

In [19]:
y_pred = model.predict(X_test.iloc[ind])
y_pred


array([[0.96348584, 0.03651413],
       [0.00442638, 0.99557364],
       [0.00785573, 0.99214435],
       [0.03281142, 0.96718854],
       [0.00415993, 0.9958401 ],
       [0.97993314, 0.02006686],
       [0.02482958, 0.97517043],
       [0.00256571, 0.9974343 ],
       [0.0158277 , 0.9841723 ],
       [0.00494153, 0.99505854]], dtype=float32)

In [20]:
y_pred_lst = [np.where(x > 0.5,1,0) for x in y_pred]
y_pred_lst
# [1,0] => True

[array([1, 0]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([1, 0]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1])]

In [21]:
y_test_lst = y_test[ind].tolist()
y_test_lst

[[1.0, 0.0],
 [0.0, 1.0],
 [0.0, 1.0],
 [0.0, 1.0],
 [0.0, 1.0],
 [1.0, 0.0],
 [0.0, 1.0],
 [0.0, 1.0],
 [0.0, 1.0],
 [0.0, 1.0]]

In [22]:
y_pred_lst = [x.tolist() for x in y_pred_lst]
y_pred_lst

[[1, 0],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [1, 0],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1]]

In [23]:
print((np.array(y_test_lst) == np.array(y_pred_lst)))
# so all the predictions are correct

[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]


In [ ]:
Step 4: Improve Your Model
Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
Adjust the learning rate when you compile the model. This means you will create a custom tf.keras.optimizers.Adam instance where you specify the learning rate you want. Then pass the instance to model.compile as the optimizer.
tf.keras.optimizers.Adam reference.
Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.